// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWw12VUYDmbI8L7Q_CE9D1M-tduc_gH0',
    appId: '1:867768715935:web:4d1880984b5af3f13370aa',
    messagingSenderId: '867768715935',
    projectId: 'tiktok-new-ad110',
    authDomain: 'tiktok-new-ad110.firebaseapp.com',
    storageBucket: 'tiktok-new-ad110.firebasestorage.app',
    measurementId: 'G-QDJHVC1BNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNzm7Qa9SZIjC309-RBO0Lz2fJL9el4qA',
    appId: '1:867768715935:android:86299948d1c155ae3370aa',
    messagingSenderId: '867768715935',
    projectId: 'tiktok-new-ad110',
    storageBucket: 'tiktok-new-ad110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIw4gNIYiOV1lE6J9F1IhUT9n32Vpc8E',
    appId: '1:867768715935:ios:19f534c06710dc193370aa',
    messagingSenderId: '867768715935',
    projectId: 'tiktok-new-ad110',
    storageBucket: 'tiktok-new-ad110.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOIw4gNIYiOV1lE6J9F1IhUT9n32Vpc8E',
    appId: '1:867768715935:ios:19f534c06710dc193370aa',
    messagingSenderId: '867768715935',
    projectId: 'tiktok-new-ad110',
    storageBucket: 'tiktok-new-ad110.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWw12VUYDmbI8L7Q_CE9D1M-tduc_gH0',
    appId: '1:867768715935:web:6c8b4cf054ac61f03370aa',
    messagingSenderId: '867768715935',
    projectId: 'tiktok-new-ad110',
    authDomain: 'tiktok-new-ad110.firebaseapp.com',
    storageBucket: 'tiktok-new-ad110.firebasestorage.app',
    measurementId: 'G-0XHEV8TZNE',
  );
}
